version: "3"

services:

  geth:
    image: "ethereum/client-go:v1.8.12"
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - ${PWD}/.ethereum:/root/.ethereum
    expose:
      - "8545"
    networks: 
      - eth
    command:
      - --rpc
      - --rpcapi="debug,eth,net,shh,txpool,web3"
      - --rpcaddr=geth
      - --rpcvhosts=*
      - --txpool.globalslots=20000 
      - --txpool.accountqueue=256
      - --txpool.globalqueue=20000
      - --syncmode=full
      - --cache=1024
      - --maxpeers=100

  nginx:
    image: "nginx:1.14.0"
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/auth.txt:/etc/nginx/auth.txt:ro
      - ${PWD}/log:/var/log/nginx
    networks:
      - eth
    depends_on:
      - geth

networks:
  eth:
