version: "3"

services:
  parity:
    build: .
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
    volumes:
      - ${PWD}/.parity:/home/parity/.local/share/io.parity.ethereum
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --no-config
      - --no-discovery
      - --identity=testrpc
      - --auto-update=none
      - --tracing=on
      - --chain=/home/parity/genesis.json
      - --unsafe-expose=all
      - --min-gas-price=0
      - --ipc-apis=all
      - --jsonrpc-experimental
      - --jsonrpc-interface=all
      - --jsonrpc-apis=all
      - --jsonrpc-cors=all
      - --jsonrpc-server-threads=4
      - --ws-interface=all
      - --ws-origins=all
      - --ws-apis=all
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
