apiVersion: v1
kind: Service
metadata:
  name: geth
spec:
  ports:
    - protocol: TCP
      targetPort: 8545
      port: 8545
      name: http
    - protocol: TCP
      targetPort: 8546
      port: 8546
      name: websoket
    - protocol: TCP
      targetPort: 8551
      port: 8551
      name: authrpc
  selector:
    app: geth
---
apiVersion: v1
kind: Service
metadata:
  name: prysm
spec:
  ports:
    - protocol: TCP
      targetPort: 4000
      port: 4000
      name: grpc
  selector:
    app: prysm
