version: "3"

services:
  geth:
    image: "ethereum/client-go:v1.9.2"
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - ${PWD}/.ethereum:/root/.ethereum
    expose:
      - "8545"
    networks:
      - eth
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --rpc
      - --rpcapi
      - "eth,txpool,net,web3"
      - --rpcaddr=geth
      - --rpcvhosts=*
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  nginx:
    image: "nginx:1.14.0"
    restart: unless-stopped
    ports:
      - "10240:10240"
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/auth.txt:/etc/nginx/auth.txt:ro
    networks:
      - eth
    depends_on:
      - geth
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  eth:
