version: "3"

services:
  parity:
    image: parity/parity:v2.3.9
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
    volumes:
      - ${PWD}/data:/home/parity/.local/share/io.parity.ethereum
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --no-ui
      - --no-dapps
      - --no-config
      - --no-ws
      - --tracing=on
      - --auto-update=none
      - --max-peers=100
      - --jsonrpc-interface=all
      - --jsonrpc-apis=safe
      - --jsonrpc-hosts=all
      - --jsonrpc-threads=8
      - --jsonrpc-cors=all
      - --jsonrpc-server-threads=8
      - --jsonrpc-max-payload=10
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
